# Site settings
title: Aaron Aycock
description: 'All things Wi-Fi and IoT'
url: 'https://blog.aaronaycock.com'
baseurl: ''
google_analytics: 'UA-G-SB9FLNSTSG'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Aaron Aycock'
  email: aaron.aycock@gmail.com
  #twitter_username: aaronaycock
  # facebook_username: joshgerdes
  #github_username:  aaycock
  linkedin_username:  aaronaycock

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 8
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
